function choice = artifactTypeMismatchDialog(loadedTypes, guiTypes)
    % Custom dialog to handle artifact type mismatches with clear instructions

    dlgWidth = 660;
    dlgHeight = 320;

    d = dialog('Position',[300 300 dlgWidth dlgHeight], ...
               'Name','Artifact Type Mismatch', ...
               'WindowStyle','modal');

    % === Header: Explanation ===
    uicontrol('Parent',d, 'Style','text', ...
        'Position',[20 dlgHeight-70 dlgWidth-40 50], ...
        'String', 'There is a mismatch between the artifact types in the loaded annotation file and in the current GUI.', ...
        'FontWeight','bold', ...
        'FontSize', 13, ...
        'HorizontalAlignment','left');

    % === Show loaded vs GUI ===
    uicontrol('Parent',d, 'Style','text', ...
        'Position',[20 dlgHeight-125 dlgWidth-40 40], ...
        'String', sprintf('Annotation file types: %s', strjoin(loadedTypes, ', ')), ...
        'HorizontalAlignment','left');

    uicontrol('Parent',d, 'Style','text', ...
        'Position',[20 dlgHeight-145 dlgWidth-40 40], ...
        'String', sprintf('GUI types: %s', strjoin(guiTypes, ', ')), ...
        'HorizontalAlignment','left');

    % === "How to proceed" heading ===
    uicontrol('Parent',d, 'Style','text', ...
        'Position',[20 dlgHeight-175 dlgWidth-40 20], ...
        'String','How would you like to proceed?', ...
        'FontWeight','bold', ...
        'FontSize', 11, ...
        'HorizontalAlignment','left');

    % === Option 1 ===
    uicontrol('Parent',d, 'Style','pushbutton', ...
        'Position',[20 dlgHeight-210 200 30], ...
        'String','Rewrite GUI from annotation', ...
        'Callback',@(src,evnt) setChoice('Rewrite'));

    uicontrol('Parent',d, 'Style','text', ...
        'Position',[230 dlgHeight-215 dlgWidth-250 30], ...
        'String','Overwrites GUI artifact types with those from the annotation file. Extra GUI types will be removed.', ...
        'HorizontalAlignment','left', ...
        'FontSize',8);

    % === Option 2 ===
    uicontrol('Parent',d, 'Style','pushbutton', ...
        'Position',[20 dlgHeight-250 200 30], ...
        'String','Match by artifact name', ...
        'Callback',@(src,evnt) setChoice('Match'));

    uicontrol('Parent',d, 'Style','text', ...
        'Position',[230 dlgHeight-260 dlgWidth-250 40], ...
        'String',['Keeps extra GUI types. Loads annotations only where names match (case-insensitive).' ...
                  ' Existing annotations for unmatched types are preserved.'], ...
        'HorizontalAlignment','left', ...
        'FontSize',8);

    % === Cancel ===
    uicontrol('Parent',d, 'Style','pushbutton', ...
        'Position', [20 dlgHeight-290 200 30], ...
        'String','Cancel', ...
        'Callback',@(src,evnt) setChoice('Cancel'));

    % Wait for user choice
    choice = [];
    uiwait(d);

    % --- Nested function to store choice ---
    function setChoice(val)
        choice = val;
        delete(d);
    end
end
